version: "3.3"

services:
  db:
    image: akiunlocks/postgres-takehome:latest
    environment: &db_conf
      POSTGRES_USER: user
      POSTGRES_PASSWORD: super-secret-password
      POSTGRES_DB: test
      POSTGRES_HOST: db
      POSTGRES_PORT: '5432'
    ports: ['5432:5432']
  app:
    build: .
    depends_on: [db]
    environment: *db_conf
    ports: ['5000:5000']